name: intake_xrviz
channels:
  - conda-forge
dependencies:
  - intake
  - intake-xarray
  - nodejs
  - pip
  - pip:
       - "--editable=git+https://github.com/intake/xrviz@master#egg=intake_xrviz"
  - metpy
  - geoviews
  - jupyter=1.0.0
  - jupyterlab=1.0.2